<?php
// src/utils/cities.php
function getTurkiyeSehirleri() {
    return [
        'Adana'      => 'Şakirpaşa Havalimanı (ADA)',
        'Ankara'     => 'Esenboğa Havalimanı (ESB)',
        'Antalya'    => 'Antalya Havalimanı (AYT)',
        'Balıkesir'  => 'Balıkesir Körfez Havalimanı (BZI)',
        'Batman'     => 'Batman Havalimanı (BAL)',
        'Bodrum'     => 'Milas-Bodrum Havalimanı (BJV)',
        'Bolu'       => 'Bursa Yenişehir Havalimanı',
        'Bursa'      => 'Yenişehir Havalimanı (YEI)',
        'Dalaman'    => 'Dalaman Havalimanı (DLM)',
        'Denizli'    => 'Çardak Havalimanı (DNZ)',
        'Diyarbakır' => 'Diyarbakır Havalimanı (DIY)',
        'Erzurum'    => 'Erzurum Havalimanı (ERZ)',
        'Eskişehir'  => 'Hasan Polatkan Havalimanı (AOE)',
        'Elazığ'     => 'Elazığ Havalimanı (EZS)',
        'Gaziantep'  => 'Oğuzeli Havalimanı (GZT)',
        'Hatay'      => 'Hatay Havalimanı (HTY)',
        'İstanbul'   => 'İstanbul Havalimanı (IST)',
        'İzmir'      => 'Adnan Menderes Havalimanı (ADB)',
        'Kahramanmaraş' => 'Kahramanmaraş Havalimanı (KCM)',
        'Kars'       => 'Kars Havalimanı (KSY)',
        'Kastamonu'  => 'Kastamonu Havalimanı (KFS)',
        'Kayseri'    => 'Erkilet Havalimanı (ASR)',
        'Konya'      => 'Konya Havalimanı (KYA)',
        'Malatya'    => 'Erhaç Havalimanı (MLX)',
        'Mardin'     => 'Mardin Havalimanı (MQM)',
        'Muş'        => 'Muş Havalimanı (MSR)',
        'Nevşehir'   => 'Kapadokya Havalimanı (NAV)',
        'Ordu'       => 'Ordu-Giresun Havalimanı (OGU)',
        'Rize'       => 'Rize-Artvin Havalimanı (RZV)',
        'Samsun'     => 'Çarşamba Havalimanı (SZF)',
        'Siirt'      => 'Siirt Havalimanı (SXZ)',
        'Sinop'      => 'Sinop Havalimanı (NOP)',
        'Şanlıurfa'  => 'GAP Havalimanı (GNY)',
        'Şırnak'     => 'Şırnak Havalimanı (NKT)',
        'Tekirdağ'   => 'Çorlu Havalimanı (TEQ)',
        'Tokat'      => 'Tokat Havalimanı (TJK)',
        'Trabzon'    => 'Trabzon Havalimanı (TZX)',
        'Uşak'       => 'Uşak Havalimanı (USQ)',
        'Van'        => 'Ferit Melen Havalimanı (VAN)',
        'Zonguldak'  => 'Zonguldak Havalimanı (ONQ)',
    ];
}
?>
